export default {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',

    DELETE_PRODUCTS: ' DELETE_PRODUCTS',

    UPDATE_PRODUCT_AMOUNT: 'UPDATE_PRODUCT_AMOUNT',

    SET_TOTAL: 'SET_TOTAL',
    CLEAR_ERROR:'CLEAR_ERROR',

}
